# Continuous Control

---

In this notebook, you will learn how to use the Unity ML-Agents environment for the second project of the [Deep Reinforcement Learning Nanodegree](https://www.udacity.com/course/deep-reinforcement-learning-nanodegree--nd893) program.

### 1. Start the Environment

We begin by importing the necessary packages.  If the code cell below returns an error, please revisit the project instructions to double-check that you have installed [Unity ML-Agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md) and [NumPy](http://www.numpy.org/).

In [7]:
from unityagents import UnityEnvironment
import numpy as np
from ddpg_agent import DDPGAgent
import torch

Next, we will start the environment!  **_Before running the code cell below_**, change the `file_name` parameter to match the location of the Unity environment that you downloaded.

- **Mac**: `"path/to/Reacher.app"`
- **Windows** (x86): `"path/to/Reacher_Windows_x86/Reacher.exe"`
- **Windows** (x86_64): `"path/to/Reacher_Windows_x86_64/Reacher.exe"`
- **Linux** (x86): `"path/to/Reacher_Linux/Reacher.x86"`
- **Linux** (x86_64): `"path/to/Reacher_Linux/Reacher.x86_64"`
- **Linux** (x86, headless): `"path/to/Reacher_Linux_NoVis/Reacher.x86"`
- **Linux** (x86_64, headless): `"path/to/Reacher_Linux_NoVis/Reacher.x86_64"`

For instance, if you are using a Mac, then you downloaded `Reacher.app`.  If this file is in the same folder as the notebook, then the line below should appear as follows:
```
env = UnityEnvironment(file_name="Reacher.app")
```

In [2]:
env = UnityEnvironment(file_name='Reacher.app')

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		goal_size -> 5.0
		goal_speed -> 1.0
Unity brain name: ReacherBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 33
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): 4
        Vector Action descriptions: , , , 


Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

In [3]:
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

### 2. Examine the State and Action Spaces

In this environment, a double-jointed arm can move to target locations. A reward of `+0.1` is provided for each step that the agent's hand is in the goal location. Thus, the goal of your agent is to maintain its position at the target location for as many time steps as possible.

The observation space consists of `33` variables corresponding to position, rotation, velocity, and angular velocities of the arm.  Each action is a vector with four numbers, corresponding to torque applicable to two joints.  Every entry in the action vector must be a number between `-1` and `1`.

Run the code cell below to print some information about the environment.

In [4]:
# reset the environment
env_info = env.reset(train_mode=True)[brain_name]

# number of agents
num_agents = len(env_info.agents)
print('Number of agents:', num_agents)

# size of each action
action_size = brain.vector_action_space_size
print('Size of each action:', action_size)

# examine the state space 
states = env_info.vector_observations
state_size = states.shape[1]
print('There are {} agents. Each observes a state with length: {}'.format(states.shape[0], state_size))
print('The state for the first agent looks like:', states[0])

Number of agents: 1
Size of each action: 4
There are 1 agents. Each observes a state with length: 33
The state for the first agent looks like: [ 0.00000000e+00 -4.00000000e+00  0.00000000e+00  1.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -1.00000000e+01  0.00000000e+00
  1.00000000e+00 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  5.75471878e+00 -1.00000000e+00
  5.55726671e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
 -1.68164849e-01]


### 3. Take Random Actions in the Environment

In the next code cell, you will learn how to use the Python API to control the agent and receive feedback from the environment.

Once this cell is executed, you will watch the agent's performance, if it selects an action at random with each time step.  A window should pop up that allows you to observe the agent, as it moves through the environment.  

Of course, as part of the project, you'll have to change the code so that the agent is able to use its experience to gradually choose better actions when interacting with the environment!

In [ ]:
env_info = env.reset(train_mode=False)[brain_name]     # reset the environment    
states = env_info.vector_observations                  # get the current state (for each agent)
scores = np.zeros(num_agents)                          # initialize the score (for each agent)
while True:
    actions = np.random.randn(num_agents, action_size) # select an action (for each agent)
    actions = np.clip(actions, -1, 1)                  # all actions between -1 and 1
    env_info = env.step(actions)[brain_name]           # send all actions to tne environment
    next_states = env_info.vector_observations         # get next state (for each agent)
    rewards = env_info.rewards                         # get reward (for each agent)
    dones = env_info.local_done                        # see if episode finished
    scores += env_info.rewards                         # update the score (for each agent)
    states = next_states                               # roll over states to next time step
    if np.any(dones):                                  # exit loop if episode finished
        break
print('Total score (averaged over agents) this episode: {}'.format(np.mean(scores)))

When finished, you can close the environment.

In [ ]:
env.close()

### 4. It's Your Turn!

Now it's your turn to train your own agent to solve the environment!  When training the environment, set `train_mode=True`, so that the line for resetting the environment looks like the following:
```python
env_info = env.reset(train_mode=True)[brain_name]
```

In [12]:
def run(episodes):
    device = 'cpu'
    for episode in range(episodes):
        done = False
        env_info = env.reset(train_mode=True)[brain_name]
        states = env_info.vector_observations 

        while not done:
#             states = torch.from_numpy(states).float().unsqueeze(0).to(device)
            actions = np.random.randn(num_agents, action_size) # select an action (for each agent)
            actions = agent.act(states)
            print(actions)
            actions = np.clip(actions, -1, 1)                  # all actions between -1 and 1
            env_info = env.step(actions)[brain_name]           # send all actions to tne environment
            next_states = env_info.vector_observations         # get next state (for each agent)
#             rewards = env_info.rewards                         # get reward (for each agent)
            dones = env_info.local_done                        # see if episode finished
#             scores += env_info.rewards                         # update the score (for each agent)
            states = next_states  

In [13]:
run(1)

[[-0.27526722 -0.11589276  2.16242327 -0.49904821]]
[[ 1.22045332 -1.61512503 -0.75330612  0.02710718]]
[[ 0.25869279 -1.51806799 -0.52099326  1.34234344]]
[[-0.23838993  1.75259181  0.72609987  0.50029526]]
[[ 1.07508069 -0.97563573 -0.78714293 -0.51712498]]
[[-0.82932268 -0.00184588 -1.27420944 -0.50780528]]
[[ 0.96512082 -0.63408661  0.48596824 -1.17131614]]
[[ 0.6949632   0.18024489  0.69328768 -0.41284653]]
[[-1.40040785 -1.88594929  1.9151777  -0.10097587]]
[[ 1.08497721 -1.79187467 -0.10926844 -0.11131852]]
[[ 1.674461    1.20001802 -0.05578128  0.45238343]]
[[-1.21251024 -1.07037651 -0.12850564 -1.05158086]]
[[0.42750373 0.11483528 0.08200035 0.42070252]]
[[0.84422487 0.91445651 0.97986658 0.84654167]]
[[ 0.28704544 -0.43077555  0.5810651   1.27925712]]
[[ 2.02113391  0.78418718 -0.2146388  -0.82245151]]
[[1.54237045 1.7998524  1.42358886 0.06944443]]
[[0.65355334 1.00832111 0.85419699 1.37205977]]
[[-0.06030262 -2.23102618 -1.49199062  2.62501116]]
[[ 0.99607447  0.27949715 -1

[[-0.82721079 -0.5314781   1.41190802  0.01958915]]
[[-1.09381197 -0.36831803  1.56861395 -0.84133883]]
[[ 0.32949346 -0.06721504 -1.26498006 -0.07708449]]
[[ 0.90095861 -1.23752476 -1.26603942 -0.62319961]]
[[ 0.21472685  1.19720671 -1.99295172 -0.20241362]]
[[-0.91406385 -0.77265727  2.17932513 -2.64131418]]
[[-0.04212563  1.57092979  1.45289558 -0.24762933]]
[[-0.62631193 -0.42017745 -0.28782094 -0.21845349]]
[[ 0.80340015 -0.03539476  0.52769616  0.46196456]]
[[ 0.59213337 -1.82816249 -0.06143625 -1.67222995]]
[[-1.11471388  1.58775291  0.58100189  1.03050441]]
[[ 0.93122876 -0.60821959  0.59447405  1.18263965]]
[[-0.84690997  1.19531167 -0.49987771  0.99008946]]
[[-1.30046211 -0.56764806 -1.77995058  0.65790809]]
[[-0.2075886   0.25724436 -0.16725109 -0.13862268]]
[[ 1.02673829 -0.72683819  0.33624439  0.43038578]]
[[-1.00834383 -0.56070517  0.04553415 -1.53559645]]
[[ 1.53945253 -1.07759913 -0.37100505 -0.85863019]]
[[-1.23054375 -0.34770258  0.39636965 -1.17318281]]
[[-0.4880417

[[-0.03461443 -0.05633486 -2.59031654  0.77549116]]
[[ 0.216838   -1.14712677  0.43326201 -0.89021819]]
[[ 1.01280318 -0.58993291  0.57048616  0.78715963]]
[[0.09011408 0.45745769 0.14734885 1.60989849]]
[[-1.01122528 -0.31532441  1.23366978  0.49254865]]
[[-0.3620052   0.49504438 -1.2437561  -0.17370967]]
[[-0.08240985 -1.21220168 -0.24371973 -1.47395177]]
[[ 0.51957376 -0.13706838 -0.28599382 -0.37035433]]
[[ 1.28415315  0.58586547 -1.01313577  0.29206651]]
[[-0.5869584  -0.89410245 -0.07447003  2.14945071]]
[[ 0.30515878  0.0961497  -0.46686213  0.17678773]]
[[ 0.03017921  0.07602809 -1.50691078  0.40994679]]
[[-0.04627931 -0.45496835  0.49935106 -0.09935899]]
[[-0.68701893 -0.53978688 -1.59976527 -0.88794949]]
[[ 1.52761247 -1.04004481 -0.34058258  0.32144318]]
[[-1.228208    1.96041007 -0.19468953  1.1933083 ]]
[[-0.11954737  0.29828572 -1.81423784 -0.32104615]]
[[ 0.14271832  1.62246181 -0.28935331 -0.33644745]]
[[-0.29294512 -0.26819794  0.01152204  0.04181519]]
[[-0.40053903  0

[[-0.03645644  1.44730905  0.10435896  0.53466785]]
[[ 0.32616718  0.0743282   0.6904923  -1.90052602]]
[[-1.57233584  2.05023184 -0.50300975  0.33647122]]
[[ 0.31398264 -1.2025984  -1.48487233 -0.01132492]]
[[-1.62837531  0.82984161 -0.26859752  0.32472419]]
[[-2.58840118  1.13352987  0.21293407 -1.81660608]]
[[ 0.22686083 -0.6872186  -1.84322493 -0.20641001]]
[[1.31156142 1.91559054 1.46092513 0.45056493]]
[[-0.26107895 -0.67511191  0.37159851  0.026246  ]]
[[-1.19429427  0.61455557  1.26039396  0.59216729]]
[[-0.35419966  0.84640672  1.21887176 -0.06238606]]
[[-0.80939174  0.08838204  0.42536108 -0.84432324]]
[[-0.40555861 -0.42083797  1.57840665  0.76638064]]
[[-0.38800605 -0.92042551 -1.46027184  0.48701092]]
[[0.95560722 0.66627687 0.18486786 0.19605346]]
[[-0.30223322  0.24109112 -0.03527762  0.03711543]]
[[-0.38539228 -0.15622171 -0.78569776 -1.12883102]]
[[-0.35192677  0.70643062 -1.63095244  1.08040167]]
[[-0.39050046 -0.41956733 -1.23715488 -0.31145389]]
[[ 1.23608301  1.415

[[ 0.35699593 -2.01387818 -1.86338495 -0.44144038]]
[[ 0.25844408  0.98627816 -0.59156759 -0.30092748]]
[[0.95989635 1.96804844 0.53766826 2.79540758]]
[[ 0.60420389  0.51783467 -0.36190635  1.74923157]]
[[ 0.38040581 -0.67441222  0.45268773 -0.17531614]]
[[0.13668455 0.10683767 0.88672727 0.47317959]]
[[ 0.08746512  0.39043382 -0.54878382 -0.68922637]]
[[ 0.45275775 -1.02384031  1.16995402  0.43525256]]
[[-0.28943812  1.07569227  1.50010121  0.71773926]]
[[-1.24550419  0.71719113  0.37961059  0.6664618 ]]
[[ 0.16755192 -0.41179572 -0.04548682  0.16476273]]
[[-1.52131222  0.7210391   0.47647365 -0.03498913]]
[[0.49172707 0.02767593 1.26679284 0.24372411]]
[[-0.38241271  0.05656078 -0.951385   -0.11901826]]
[[ 0.01444863  2.73475502 -1.07182527  0.70721884]]
[[ 0.96056629 -0.59466796 -0.50640867  0.09334365]]
[[ 0.29125906  0.1135048  -0.26197953  0.29426313]]
[[ 0.14873856 -0.80140255 -0.84533517  1.66485486]]
[[-0.73944527 -0.30248664 -0.05918223 -0.50132545]]
[[ 0.32226102  0.9731510

[[-0.05263161  0.18554611  1.59681529  0.13381305]]
[[-0.76350914  0.16615654  1.27609513  0.62379612]]
[[-0.69347282 -0.67094148 -0.27181071  2.45761833]]
[[ 1.2833658  -0.4088023   0.16880405 -0.20541439]]
[[-1.61735435 -0.14378037  0.01603296  1.18890198]]
[[-0.46847688 -0.71082355 -1.06111557 -1.90650917]]
[[-0.11841027  0.13443905  0.56895967  1.1143827 ]]
[[-0.75108706  1.84526583  0.066532   -0.58883994]]
[[ 0.45732636  0.05714793 -0.59694767  0.18766484]]
[[-1.40154781 -0.75204535  0.19903319 -0.44861499]]
[[ 2.39678297  0.27190353 -0.49015167 -3.18246753]]
[[-0.02920684  0.24784617 -0.11692583  0.62891318]]
[[ 0.32367783  1.75375462 -0.64938113 -0.70261559]]
[[-1.71220236 -1.29034935 -0.03132792  0.75796938]]
[[ 0.17091381 -0.12874578  0.00919819 -0.86133643]]
[[-0.75911788 -1.607361    1.57792162  0.80027542]]
[[ 2.20025781 -0.37012071  2.24863543 -0.80573307]]
[[ 0.39183402 -0.60533777  0.66485153 -2.91327184]]
[[ 0.90124698 -0.43808175 -0.19715634 -0.22573028]]
[[ 0.7255835

[[-0.00773131 -0.01812989  0.3264447  -1.16154754]]
[[ 0.27766081 -1.46309789  0.31473782  1.10103035]]
[[-0.02827317 -1.61404644 -0.62654148  0.48515159]]
[[ 0.37208317 -0.34151188 -1.07622514 -0.23007444]]
[[-0.27610262 -0.42811566 -0.66322543  1.4787113 ]]
[[-0.13876132  1.25643741 -0.10747217  0.03446176]]
[[ 0.96272656 -1.4076303   1.43314147  1.51902789]]
[[-0.24805472  1.95058663 -1.72442037  1.46632413]]
[[ 0.99536283  1.90166084 -0.38788593 -0.56328442]]
[[-4.52210159e-01  5.52118676e-04 -1.58595123e+00  4.59342493e-01]]
[[-0.5188115  -0.12967573  1.7232696  -0.03561936]]
[[-1.95435356 -0.50877656  0.98771405 -1.31863563]]
[[-0.1816762  -0.03527453 -1.90049075  0.68329054]]
[[ 0.17551432  1.45526233 -0.53342452  2.177373  ]]
[[-0.59035363  0.95101939  0.65584772 -1.47314188]]
[[ 0.43672039  0.74980206 -0.81197835  0.50163644]]
[[-0.12036666  0.81648528 -0.24414935  0.92252599]]
[[ 0.02616438  1.59039858 -1.15400589 -0.52683937]]
[[-1.09393044 -1.00782993  0.14773561  0.6875934

[[-0.2817985   1.51939481  0.91548458 -1.04728724]]
[[-0.88752961  1.06120904 -0.34143585 -0.52344771]]
[[ 1.50088432 -0.18438702 -0.29645183  0.46010832]]
[[-0.42658986  1.02681643  0.5106646  -1.16558426]]
[[-1.09593582 -1.49177247 -0.24653878  1.16418718]]
[[-0.53438369 -0.70853036  0.01199636 -0.54435577]]
[[ 1.65883456  2.04266311 -1.36680562  0.49829219]]
[[ 0.04511384  0.08425289  1.04855724 -0.92114626]]
[[ 0.76232396 -0.53678599  0.77955512 -0.53582509]]
[[0.31095517 0.17712539 0.53592687 0.00852017]]
[[ 0.72402934 -1.62901398 -0.06121733  1.13560556]]
[[ 1.07440508 -0.07058775 -0.23021285 -0.00668204]]
[[-0.18601581  1.26073716  0.38534354 -1.81647673]]
[[ 0.66966894  1.79602067 -1.14678962 -0.89214853]]
[[0.07447631 0.61331832 0.25977846 0.00751922]]
[[1.20157162 0.28657986 1.39236263 0.25002   ]]
[[-1.32798489 -2.03021191 -1.36362346  1.20251066]]
[[ 0.5224813   0.14456597  1.61234583 -0.15854719]]
[[ 0.57899735 -2.21591062  0.10165747 -0.98623095]]
[[ 0.88736192 -0.8497211

[[-0.08722104 -1.53331106 -0.66245226  0.5048805 ]]
[[-0.65201642 -1.10919322 -1.76037193 -0.7677567 ]]
[[ 1.58831511 -2.28489463 -1.10882435 -0.30425876]]
[[-0.77149614 -0.136508    0.67500508 -0.50967503]]
[[-0.92795955 -0.75060017 -0.40870087  0.56168729]]
[[ 0.15504788 -1.27806119  0.4685547  -0.91907742]]
[[-0.30414122  0.11114082  0.94002632  1.73834334]]
[[ 1.27735671 -1.63364665  1.10991312 -0.25644121]]
[[-1.04438104  0.86372128  0.55039848 -0.7272711 ]]
[[-0.25889451  0.32809424 -0.31091999 -0.10085115]]
[[-2.00882082  2.26832434  0.24583329 -0.29164497]]
[[ 1.73967592 -1.21098054 -1.44432299 -0.92294926]]
[[ 0.31543159  2.12356695  1.86813176 -1.038558  ]]
[[ 0.56687192 -0.25805608 -0.69236752  0.53352137]]
[[-1.54347795 -0.29225149 -1.21634879  0.48182511]]
[[-1.28035155  0.44065531 -0.83832017 -0.89825973]]
[[ 1.96555601  2.44261708 -0.30684393  0.19172778]]
[[ 1.54694683  0.37323339 -0.56180162  0.86122538]]
[[-0.63110593 -0.15400153 -0.13633592 -0.92221512]]
[[0.05181134

[[-0.86536054 -0.24643383 -1.17678153  0.25690944]]
[[-1.23994839  1.48004727 -1.69675519 -0.88219733]]
[[-0.03582705  0.08694869 -1.35852841 -2.15038238]]
[[-0.08273979  0.47981916 -0.7396421  -0.89263464]]
[[ 0.39141145 -2.03988546  0.24430856  0.67720418]]
[[-0.88598803  0.57362387  2.08119945 -0.60240334]]
[[ 0.12513605 -0.24123421  1.34349596  0.91252993]]
[[-0.26868411 -1.0514132  -0.60826514 -2.56009057]]
[[ 0.24882458  0.13367558 -0.23404005 -1.12334801]]
[[ 0.4500315  -0.47255391 -1.32827725 -0.75269741]]
[[ 2.99534741 -0.80605941 -1.09643339  1.23002691]]
[[-0.59822892 -0.093815    0.23195337 -0.8305757 ]]
[[ 0.96933602  0.68454408  1.25431305 -0.60212677]]
[[-1.12537675  1.28553119  0.65870792 -1.1707968 ]]
[[ 1.44976516 -1.96173456  0.17128944 -0.82754072]]
[[ 1.73915592 -0.91028609  0.52627723  0.90939153]]
[[ 0.02843411  1.50338903 -1.02182173  1.46858983]]
[[-0.50925244  1.86424121  1.16662888 -1.00308769]]
[[-0.70651915 -0.03655077 -0.58389701  0.31452947]]
[[-0.3047566

[[-0.38605061  0.45302057 -0.24316363 -0.23239274]]
[[-1.8465881   0.29959086  0.85583762 -1.83201316]]
[[ 2.24509873  0.34519547 -1.70903926  0.71116542]]
[[ 0.63154059 -0.31944814 -1.25663609  0.19551517]]
[[ 0.44708117 -0.78924185  0.59419173  0.8661298 ]]
[[-0.37609658 -0.19601879  0.46302196  0.1418833 ]]
[[-0.83752776 -1.68642934  0.4545809   0.82207621]]
[[ 1.43891879 -0.24009628 -0.3483002   0.91280856]]
[[ 0.56177048 -0.3902918   0.20763571  1.9960532 ]]
[[ 0.01517805  0.751415    0.68910826 -0.48514409]]
[[-1.31601995  0.03534547  1.61198982 -1.10260349]]
[[ 0.62714274 -0.16894325 -1.02526501  0.12476011]]
[[-0.73146638  0.88504693 -0.0889948  -0.59602435]]
[[ 0.81469872  0.03814783  1.41000423 -0.45351301]]
[[-0.57223157  0.38645078  0.44303984  1.24308383]]
[[ 1.45555845 -0.41381993 -1.79901997 -1.44223988]]
[[0.54088097 0.80717765 0.54643442 0.86210774]]
[[-1.79953559  1.41893426 -0.70205831  0.3378865 ]]
[[-0.56616147 -0.3791719   1.38173889 -0.86172715]]
[[-0.29763808 -0

[[ 0.67380905  0.49619742 -0.02901527 -1.89886935]]
[[ 1.164915   -0.57601897  0.03492146 -0.50191521]]
[[-0.15036096  1.63811235  0.01942951 -0.65537716]]
[[-0.1869754   2.66157866 -0.72648605  1.37417643]]
[[ 2.07844776 -0.42471441 -0.10677234 -0.68390715]]
[[ 0.54341257 -0.36159002 -0.97795991 -0.49809629]]
[[-1.16497249  0.01579222  1.89080326  0.34533011]]
[[-0.36669934  1.22611062  0.46421701  0.22738927]]
[[ 0.21651032  0.25640893 -0.39180778  0.0493037 ]]
[[-0.23504133 -0.57330612 -1.24511164  0.9337089 ]]
[[-0.96640518  2.06014697 -0.27855993  0.04768384]]
[[ 0.48646913 -1.63233689 -0.09103523  0.18616594]]
[[-0.98645012 -1.15745531  1.96921278  0.40913138]]
[[-0.54350037 -0.26667935 -1.43238567  0.6855617 ]]
[[ 0.76690056 -2.0318229   1.15729017  0.51511261]]
[[-1.90165287  1.1082518   0.14692825 -0.35521351]]
[[-0.45339295 -0.3289936   1.1470343  -0.90027105]]
[[-0.61631794  0.58242376 -0.74375698  2.01945086]]
[[-0.18142062  0.50166822  0.73794573  0.41208257]]
[[ 0.9799955

[[-0.73856935 -0.29046102 -0.92906545  0.96705504]]
[[-0.97257329 -0.01618295 -1.65238366  0.41709002]]
[[-0.7589532   0.28659472 -1.19820429 -0.55592175]]
[[-1.61750089 -1.21237771 -0.31177125 -0.13891169]]
[[ 0.10732974 -0.30189526 -0.82332499  0.19988515]]
[[-0.87757334  0.50506343  1.24728078  1.71262941]]
[[0.62166631 0.96064924 0.38254377 1.27220937]]
[[-0.5149094   1.49437622  0.86442968  0.01989914]]
[[-0.65282636  0.61449797 -0.04630009  0.49666435]]
[[ 1.5621593  -0.37790583  1.08021919 -1.08038343]]
[[ 0.44784468 -1.10343161 -0.40124493  0.84220543]]
[[ 0.06268618 -0.18776229 -0.1066215   1.09399207]]
[[-0.3610212   0.05056611  1.26753768  0.45487004]]
[[-0.12239814 -0.24264067  0.3903683   0.36539839]]
[[-0.48942716  0.91312598  0.94837346 -0.12626845]]
[[ 1.1749208  -0.67379504 -0.91525664 -0.77502044]]
[[-0.98042108 -1.29797169  1.13939775  0.14374545]]
[[ 0.02957267  0.14924718 -0.64841731 -0.11937089]]
[[-0.38201288 -1.22641035 -0.38644321  0.37103081]]
[[-0.60535462 -1

[[-0.67528553 -1.04714908  1.13233537 -0.34396743]]
[[-1.44006573 -1.22299057  0.95381584  0.11430075]]
[[-0.90688944  0.39050799  0.49762948 -1.34768958]]
[[-0.03617446  0.72911782 -0.92921629  0.94723812]]
[[-0.20699507 -1.85785498  0.72377639  0.75333488]]
[[-0.56124237  0.78915673 -0.6398888   0.45883898]]
[[ 0.21679966 -0.37881199 -0.2717132  -0.18516502]]
[[ 0.82557008 -0.09759821  0.4731717  -0.14471722]]
[[-0.1882029  -0.35545729  0.28840302 -0.93298041]]
[[2.42340185 1.55354451 0.41322963 1.42954371]]
[[ 0.28190113  1.76965725  0.09697654 -0.76913729]]
[[-1.24237025 -0.77815615 -1.18481297  0.99883955]]
[[ 0.31061984  0.92188809 -0.88105899  0.89573953]]
[[-0.3401755   2.31374274  1.3066914  -0.30768443]]
[[-1.23318268 -0.68105979 -0.98714237 -0.79225207]]
[[-0.24795916 -0.50868187  0.3417672  -0.87725329]]
[[ 1.54859566 -1.29068019  1.31356021  0.60645909]]
[[ 0.52114273 -0.07990311  0.65519131 -0.32507465]]
[[-1.15981218  0.47860324  0.26901923  0.84043092]]
[[ 0.26036409 -0

[[-1.10625388  1.7850454   0.74737524  0.12951983]]
[[0.88273855 1.38189263 0.82258324 0.42416702]]
[[-0.15821751 -1.02706459  1.11261107 -0.29657131]]
[[ 0.33470698  1.02697917 -0.68874004  2.01059698]]
[[-0.46049437  1.01118977 -1.00039934 -1.22676693]]
[[ 0.72112031  1.71937488 -1.3256625  -0.33851925]]
[[ 0.53385286 -0.23348304  0.54898861  0.44277062]]
[[-0.99955971  0.26822743  0.46982144 -0.79880572]]
[[-2.27714529  0.80445524  0.56432603 -1.30771162]]
[[-0.6676791   2.05063095 -1.11864595 -1.56090566]]
[[ 0.80303712 -1.05593906 -2.34769399  0.79375234]]
[[-0.51680806 -0.03153961 -0.99017152  0.87704488]]
[[-0.25201856 -2.70446402  0.32404423 -1.19866649]]
[[-1.07646165  0.70924459  0.7805854   0.66660462]]
[[-1.97075181 -0.26675454 -0.65827737  0.00572681]]
[[-1.02956278  1.00283907 -0.4312419  -0.57937964]]
[[ 0.25824403  0.71152197 -1.1859876  -0.4762835 ]]
[[ 1.13593964 -1.68914623 -0.51748216  1.30128898]]
[[0.3698459  2.18203796 1.43409154 0.61508396]]
[[-1.50661206 -0.074

[[-0.54560226 -1.01086313 -0.66324336  1.03379926]]
[[-0.13433367  1.04410293  0.46530373 -0.90741886]]
[[-0.58668927  1.33365803 -0.60151796  0.65533436]]
[[ 1.28774019 -1.10018734 -1.1380077   0.33195431]]
[[-0.15346486  0.09345321  0.7373996  -2.42078249]]
[[ 0.39570273  0.78592948  1.55352106 -1.44798249]]
[[ 0.68043853  0.53792122  0.75126614 -1.82376779]]
[[-0.0787194  -0.98203576  0.01534395 -0.59571944]]
[[ 1.1931996  -0.02346295 -0.556769   -0.55229538]]
[[-0.07787016  1.21668864 -1.76627713  0.70736129]]
[[ 0.85177217  0.33825975  0.50790689 -2.02220961]]
[[-0.14372447  0.54917913 -1.65424191 -0.88301071]]
[[-0.21765145  0.87302504  0.20511013  0.01871203]]
[[-1.33752993 -0.50116574 -1.58498045  0.73849798]]
[[0.00338351 0.31886792 0.41188226 0.83536793]]
[[0.93838986 1.49077953 2.35570593 0.3425074 ]]
[[-0.12094235  0.24849263  0.3782118  -0.43302276]]
[[-0.10780224  0.61219542 -1.45052277  0.33488581]]
[[-0.18617667  0.72276617  1.30148629  0.08477834]]
[[-0.78270813 -1.081

[[ 1.13562297 -0.42901212 -1.44298965  0.24786808]]
[[ 0.1324705  -0.85780974  0.0447095   0.91880199]]
[[ 0.54536289  1.27090634 -0.37727834 -0.04361164]]
[[2.36243794 0.19723506 1.06323158 1.46265968]]
[[-0.77377734 -0.39023085 -1.08904748  0.69447805]]
[[ 0.74380399 -0.56282405  0.16837801  2.3021192 ]]
[[ 0.11039917  1.65199687 -1.65214946 -0.45282961]]
[[0.61022519 0.42431337 0.36214258 0.38338764]]
[[ 1.06480209 -1.20970194  1.4125808  -0.65145865]]
[[-1.6636088  -0.54138007 -0.00970363  0.25317733]]
[[-0.62906618 -1.28226241  0.53597786  0.13018596]]
[[-1.27287356  2.49900703  1.30601713 -1.01119788]]
[[-1.4842989  -0.22709235  0.66480901  0.84072708]]
[[ 1.14888041 -1.01157981  1.40357677 -1.38227936]]
[[0.58801142 0.3332189  0.42709583 0.66833597]]
[[-0.07618791  0.30779501 -1.01855421 -0.6415176 ]]
[[ 0.09049488  0.10412392 -0.88060001 -0.42762865]]
[[-0.52382818 -0.50115154 -1.09046443  0.80254249]]
[[-0.55736411 -0.46692719  0.43384889 -3.55125955]]
[[-0.26622416  1.1043325

[[ 0.19143209 -0.24881613 -1.10592923 -0.83487938]]
[[ 1.12764234  0.47747296 -0.34421478 -0.20283561]]
[[ 0.11746361 -0.63189089 -0.33564397  0.75808231]]
[[-0.12331029 -0.46954302 -1.06548652 -0.9350665 ]]
[[ 0.9334795  -1.38374352 -0.31589872 -0.04312377]]
[[-0.40372605 -1.0078808  -0.81977816  1.48103915]]
[[-0.11744928 -0.29512966  0.31059639 -0.55632249]]
[[-0.58060889  1.47280385  0.41801081  1.82644671]]
[[ 0.31122747  0.52201267  0.55388045 -1.27694516]]
[[-0.29954159 -0.4167185  -0.46999094 -0.04950333]]
[[-0.20771257  1.4548982  -0.41283615  0.56756931]]
[[ 0.01022701  0.39282908 -0.14070488  0.68024865]]
[[-0.99811235  1.47425024  0.26230053 -0.49718375]]
[[ 1.7988625  -0.61332546 -1.2595572   0.90823007]]
[[ 1.04588926  0.85666008 -1.06547829  0.06483071]]
[[ 0.39621554 -0.08481327 -0.89019445 -0.69172459]]
[[-1.1191531   0.83472891 -0.6234784   0.48274579]]
[[ 0.07147967  0.04237815 -2.11605317 -1.90208466]]
[[-1.14412732  0.74985312 -0.42723896 -0.01514236]]
[[-0.0634545

[[-0.59028532 -0.22889017  0.97047676  1.12445723]]
[[-0.00588471  1.77135777  0.73043193 -1.15191361]]
[[-0.57388158 -0.9957372   1.20615719  0.10864582]]
[[ 0.14743438 -0.93540726  1.27476953 -0.48909636]]
[[-0.98539592  0.59431835  0.3498245  -0.03908813]]
[[ 0.05183905 -0.04503381  0.0885172  -0.05109007]]
[[ 0.51863734 -0.78719941 -0.48521264 -0.62583097]]
[[-1.0624804   0.115292   -0.96189903  1.58309159]]
[[-0.69571826 -1.04423747 -0.46839482 -1.61230185]]
[[ 1.69461782 -1.75535017  0.29826376 -1.22935375]]
[[ 0.9323344  -1.27624624  0.31183263 -0.40684289]]
[[-0.57101137 -0.89749101  0.73122483 -0.35957649]]
[[-0.8120129   2.13635113 -0.5051695   0.29153989]]
[[ 0.89535646 -0.65511865  0.48896142  0.26848547]]
[[ 0.39459835  1.83773874 -0.05651664 -0.90056045]]
[[-0.90171764  0.4088961  -1.16497847  1.18203588]]
[[ 1.69007953 -0.29843408  0.56593823 -0.53308597]]
[[ 1.47317661  1.12654604  0.50496566 -1.03498104]]
[[-1.72977979  0.60075068 -0.33959346  2.54777743]]
[[ 1.4304061

[[ 1.37195556  1.14084978 -0.67569872 -0.28530422]]
[[ 1.06660878 -2.00928528  1.7882301  -0.21142851]]
[[0.0575482  0.06039654 0.93846487 1.43449365]]
[[-0.28441561  0.06530482  0.0468326   0.22556645]]
[[0.85016428 2.03644976 0.60078417 0.41234654]]
[[-1.2085787   1.81211582 -0.9400098  -1.04216327]]
[[ 1.14216692 -1.02472643  0.21581654 -1.13491293]]
[[ 2.30387758 -1.17920035 -1.61891953  1.44815699]]
[[-2.04451754  1.7263455   0.69530725  1.19800982]]
[[ 0.56854273 -1.23746526 -0.43141537 -2.53062513]]
[[ 0.97534781  1.53152751  0.35149265 -0.07082947]]
[[-0.31500933 -1.05998324  1.7846011   0.77088564]]
[[-0.40643521  1.00564038  1.21880687  1.44929958]]
[[-1.03821509 -1.68293276 -0.09344846  0.26085067]]
[[-0.15847177 -0.76315226 -0.59067089 -0.85183155]]
[[ 1.87542398 -1.45683537 -1.21003889  1.38485014]]
[[-0.70986279  0.43397492  1.05422319  0.75019497]]
[[ 0.16828199 -0.01392826  0.446104   -0.79542615]]
[[ 0.43578765  0.16701091  0.83594649 -1.40578139]]
[[-0.78048568 -0.567

[[-0.12115637 -1.27065107  0.94539753  0.76864571]]
[[1.28727337 1.84612842 0.38175559 0.27181176]]
[[ 1.64899214 -1.30917271 -0.50260099 -0.61802683]]
[[ 1.00101068 -0.22881539  1.41854364 -0.62421225]]
[[-1.50929572  0.48440124 -0.79899633 -1.11409633]]
[[-0.576105   -0.68186592  0.31600426  0.33634032]]
[[-0.0735941   2.36461505 -0.48786089 -0.00636644]]
[[-0.75449454  1.76700024  0.71270212  0.13607163]]
[[-0.59870631  0.7537782  -0.45721869 -1.56434913]]
[[ 0.30102003 -1.14555923  0.94660039  1.38166573]]
[[-0.91311764 -0.33168892  0.74385415 -1.40599545]]
[[0.30056455 2.44453585 0.18765579 0.09205556]]
[[-2.05524106 -0.6851069   0.40827173 -0.041788  ]]
[[0.68589883 0.22740755 0.29446032 0.52553506]]
[[ 1.14450485 -0.62352734 -0.68077004 -0.42774284]]
[[ 0.88488267 -0.14884854 -0.3016885  -0.12492318]]
[[-1.3057339   0.01324978 -1.17841433 -1.18967094]]
[[ 0.85504858 -1.35273255 -0.72869905  0.69028261]]
[[-0.04257361  1.41797568  0.31573466 -0.56613653]]
[[-0.81791625 -0.5147718

[[ 0.89466787 -0.39991389  0.32032155  0.80913639]]
[[ 2.62187919 -0.22818984 -2.07780787  0.57472388]]
[[-0.15592198  0.64837758  0.36466447  0.8296064 ]]
[[-0.25319918 -0.84765603  0.34583509  0.21042349]]
[[ 0.59453822  1.19964565 -1.10592374  0.24309077]]
[[ 0.57221108 -1.79654542  0.49310424 -0.65856996]]
[[ 1.01080243  2.18760996 -0.60047248 -0.65909126]]
[[-0.63153487 -0.53611564  1.11389452 -0.57634022]]
[[ 0.08180459  0.78422512 -1.09226085  1.47725199]]
[[-0.36308043 -0.07209625  0.55157606  0.62214521]]
[[ 0.094961   -1.95845256 -1.20889679  2.55650849]]
[[-0.19522635 -0.11941916 -1.66241427 -1.80647316]]
[[-1.65237125 -0.15559058  1.05605717  2.19787095]]
[[-0.87892378  0.75265728  0.09506654  0.01234994]]
[[ 1.58186421 -1.08385083 -1.52411765 -0.37175109]]
[[-0.84180925  0.10764582  1.01685435  1.98742901]]
[[ 1.60817245  0.81396823 -0.10831305 -0.05354027]]
[[-0.48926936  0.11821971  0.3151644  -0.33258117]]
[[-0.24711484 -0.25081057 -0.43990064  0.32948871]]
[[ 0.2555955

[[ 0.98002563  0.2478232   0.01865022 -0.89219354]]
[[ 1.87220435  0.97157395  0.280651   -0.52172955]]
[[0.38336973 0.729236   0.37042446 0.42223676]]
[[ 0.65652135 -2.41210301  1.07061852  0.81057019]]
[[0.46696074 0.56202832 0.16881724 0.53655367]]
[[-0.38389147 -0.18422756 -0.4881458  -1.24597654]]
[[ 1.83003663  0.77616385 -0.15759851 -0.8388751 ]]
[[ 0.55890858 -0.27835958 -1.05676297  0.88468715]]
[[ 1.6289675 -1.2927094  0.0478214  1.7567099]]
[[-0.47277319  0.82071497 -1.71769174  0.92168782]]
[[-0.9150283  -2.06443917  1.95589632 -0.4678702 ]]
[[ 0.42364157 -2.25334065  1.46485998 -1.14102255]]
[[-1.23439951 -0.69917761  0.83370685  1.00437379]]
[[ 0.86529211 -1.33986605 -0.059441   -1.24212489]]
[[-0.15015598  0.18390001  0.79956371 -0.72658722]]
[[ 0.11460104 -0.08825602  1.26040967  0.85871091]]
[[ 1.24278954  1.24552273 -1.16315159  0.54191224]]
[[-0.8127562  -0.04140169 -0.44807874 -1.19944278]]
[[-0.25134584 -0.33134703  1.40350633 -0.9802019 ]]
[[-1.82768793 -0.5023603

[[ 0.19056982 -1.30262257 -2.05327651 -0.82197122]]
[[ 0.70750317 -1.47019983  0.26128409 -0.5186986 ]]
[[-0.64917668 -0.94249552  1.45812788  0.07084628]]
[[-0.70870898  0.68570445 -1.26920146 -0.23307579]]
[[0.24534768 0.35525867 1.47161928 1.69197259]]
[[-0.50940255  0.07738983 -1.16389781 -0.21752643]]
[[-0.76576166 -0.81635492 -0.25886114  0.79713483]]
[[ 0.2919627   0.03929585 -1.79417559  0.69062042]]
[[ 0.5346882  -2.02959153 -0.08333268  0.15453095]]
[[ 0.55026591 -0.95526308 -0.37930338  1.06352351]]
[[-0.12243144  0.99203254 -1.09867538 -2.17248691]]
[[-0.33191892 -0.52115373  0.85643811  1.87085366]]
[[ 0.01000662  0.81650507 -1.0211228  -0.12898928]]
[[ 1.47309731 -1.68795781  0.34696463  0.91894874]]
[[ 0.41669055  1.56200705  0.33700414 -0.74826112]]
[[-0.68267323 -1.58091233  0.37902724 -0.67207232]]
[[ 0.38060935 -0.31553484  2.1171707  -1.36848714]]
[[-0.78426885 -0.9512606  -0.5910427   1.4325885 ]]
[[ 1.56749016 -1.67246937 -0.43039592 -0.06910686]]
[[-0.40247017  0

[[ 0.80193928 -1.15433809 -0.19581247  0.64707209]]
[[0.68741362 0.05993185 0.75438161 1.23240396]]
[[ 1.40645983  0.15631752 -2.06161191 -0.67152051]]
[[ 0.68067494 -0.0881287  -0.35512104 -0.45702769]]
[[-0.69033398  0.57819419  0.99130684  0.93078436]]
[[ 0.05360338  0.48562373 -0.69704067  0.3631923 ]]
[[-0.11627135 -0.51246265 -0.47565468 -0.84537921]]
[[ 1.18550698 -0.46202844  0.97282493 -1.28656182]]
[[-1.37547077  0.00735385 -0.31210307 -0.41786555]]
[[-0.03415002  0.78216786 -0.19035595 -1.07709155]]
[[ 0.63836491 -1.68181334 -0.42035023  1.0604552 ]]
[[-0.75358714 -0.15659487  2.20588394 -0.83200724]]
[[ 1.84388611  0.07150293 -1.03523845 -1.0846567 ]]
[[-0.37950655 -1.6736752   1.01064667 -0.54984532]]
[[ 0.46362591  0.15933972 -0.3213072   0.21330696]]
[[ 0.82804193  1.810334   -1.10404389 -1.30886436]]
[[ 0.72273212 -0.21417222  1.12607505 -1.60562554]]
[[ 0.95048158  0.64835352 -2.2404403  -0.34809108]]
[[-1.97144228  0.14299984 -0.62440079  1.19887495]]
[[ 0.46313219 -0

[[ 0.27649758 -0.28787591 -0.58408301 -0.06830919]]
[[0.71375868 0.90249179 0.828921   0.11134751]]
[[-1.18339755 -1.2673075   0.17346488  0.01583768]]
[[ 0.79271056  1.16566875 -0.01064375  0.79742631]]
[[ 0.61592011  0.97544777  0.64531628 -1.03101823]]
[[ 1.23315913 -0.03020868 -0.86202405  1.22403728]]
[[ 1.91644303 -0.45821977 -0.36530259  0.68033071]]
[[-0.89728526 -1.66551467 -2.00575719  0.52477604]]
[[-0.52306416  2.09605124  0.18708151 -0.43819779]]
[[1.82165173 2.24574707 0.16344959 0.03156717]]
[[-0.40818574 -0.15095352 -0.29183656  0.18523375]]
[[-0.99709981 -0.52702641  1.77376562 -0.01584675]]
[[-1.25457729 -1.48157232 -0.70254113  0.78140968]]
[[ 1.76608163  1.56006951 -1.71978413  1.15900249]]
[[ 1.18001783 -0.20320891  0.15331579  0.13540471]]
[[-1.5365551   1.6753498  -0.1631401   1.30798199]]
[[ 0.1699517   0.3692712   2.21910445 -1.87905832]]
[[ 0.87464518 -0.6232784  -0.90829235 -0.55124006]]
[[-1.86625295 -1.2597041   0.1900242   1.98439303]]
[[ 2.74526083  0.975

[[-0.31709398  1.42437423 -0.79514001  1.29654928]]
[[-0.09313201 -0.66232653  1.02441228 -0.8789537 ]]
[[-0.54753201 -0.38742311 -0.86684941  1.2884348 ]]
[[-0.83316066 -1.02605838  0.07439816 -0.2259331 ]]
[[ 0.38255652  1.01462362 -0.87623793  1.83313924]]
[[ 1.34613319  0.3068056  -0.01951458  0.51192644]]
[[-0.22539391 -0.15635913  0.32968675  0.08032546]]
[[-1.55302222 -0.63616485  0.76158006  1.47377005]]
[[0.06842728 1.34458393 0.28867437 0.39805543]]
[[ 0.99935835 -0.83479594 -0.09549065  3.03786145]]
[[0.51039    0.04512182 1.70292408 1.27556302]]
[[0.28497493 0.49704851 0.37208678 1.54394322]]
[[0.31127678 1.54597719 1.20331485 0.66373252]]
[[ 0.59707891  0.52409784  0.53805303 -0.34294192]]
[[-0.4362066  -2.07385278  1.54282812  0.51398555]]
[[ 0.3793156   0.15441726 -0.05121981  1.89499201]]
[[1.10140112 0.9551055  0.50994056 0.04312174]]
[[ 0.49470689  1.39436454 -0.86905829 -1.03363017]]
[[-0.98166754 -0.14053145  1.47790024 -0.96727028]]
[[ 0.60731039  0.47533036 -0.076

[[ 0.72429412 -1.2596069   0.07985501  1.98794024]]
[[ 2.48599912  0.54248212  0.02537428 -1.02921142]]
[[-0.06023567 -0.27676966 -0.42346172 -1.22897775]]
[[-0.27035583 -0.51079941  0.27638442 -0.96856755]]
[[-0.58277245 -1.94004674 -0.05309203  0.07716302]]
[[-0.17900072  0.64915996  1.54435468  0.20842926]]
[[-0.87386431 -0.01048575  0.10613976  0.42158675]]
[[-0.05452558  1.79785108 -0.57442784 -0.05338863]]
[[ 0.83074334  1.19162859  0.3343226  -1.0405452 ]]
[[-1.05522825  0.69983087 -0.59301224  0.28134726]]
[[-2.08667104  0.51109445  0.60095259 -0.43898462]]
[[-0.55231843 -0.59383304 -0.37858429 -2.48764685]]
[[-0.52469638  0.82972088 -1.23162039 -0.39366999]]
[[-0.02113772 -0.90666184  1.46079036  0.11778524]]
[[ 0.88129582  0.76627974 -0.05540266 -1.07333282]]
[[ 0.25571509 -0.44619835  0.39972714  0.27510194]]
[[0.16875426 0.31272264 0.63709167 0.00068828]]
[[0.13746877 0.10967754 1.82628227 1.69520258]]
[[-0.0402464  -0.01279107 -1.94843775 -1.84723513]]
[[-0.711579   -1.902

[[ 0.67533878 -1.29977892  2.00627861 -0.44661303]]
[[-1.63390795 -0.26906196  0.09771741  1.23585097]]
[[ 0.82755669 -0.518165    0.61291129  1.38041498]]
[[ 0.57264938  1.53321346  0.25024144 -0.24037811]]
[[1.08462821 1.18475101 0.597848   0.3878448 ]]
[[-0.42263029 -1.16942073 -1.97629698  0.13419877]]
[[ 0.63163438  0.71131135 -1.11795438  0.16834661]]
[[-0.13488605  1.65465108 -1.42288621  0.18650424]]
[[-1.35929922 -0.15512316  0.897604    1.40337408]]
[[ 1.01813433 -0.34894104  0.91608082  0.72335993]]
[[ 1.43839443  0.00725381 -0.19412864 -0.4941096 ]]
[[ 0.24267045 -0.24796123  0.52387632 -1.41552105]]
[[-0.64367748  0.20662285  0.01238459  1.67483363]]
[[0.82083945 0.90165286 0.14326693 1.29974735]]
[[-0.02028708 -0.2500929  -0.48878044  0.81072504]]
[[ 0.55051084  1.0103054   0.88035647 -0.49556923]]
[[ 1.6247078  -1.03520828  0.61942873  0.34547879]]
[[-0.01981751 -0.628875    0.46317733  1.41926768]]
[[ 1.36353215  0.99742535 -0.96666167 -0.68563309]]
[[-0.69636168  0.310

[[-1.27428474 -1.97108852  1.11738822  0.31937474]]
[[1.6796661  0.40504967 1.52925321 0.14368355]]
[[ 0.32841367  0.06072249  1.49264273 -0.21568383]]
[[-1.38092903  1.34736566 -0.37832338 -1.26475563]]
[[0.60278673 0.36578547 0.21553443 0.02167768]]
[[ 0.23846184 -1.53801406 -0.10915878 -0.73657673]]
[[-0.01485775 -0.06252089  0.84932202  1.27177133]]
[[-1.70630716 -0.22832049 -0.04366358  0.44470623]]
[[ 0.3101104   0.12467421 -1.12548426  0.25468628]]
[[ 0.81891999 -0.51858955  0.60887586  1.73361428]]
[[-0.359767    2.5726269   0.04822918  1.9799186 ]]
[[ 0.43694463  0.312361    1.86742418 -1.73075798]]
[[ 6.23577976e-01 -1.89697874e+00  8.72928710e-04 -7.05738387e-01]]
[[-0.16994399  0.0511884   1.29203218  0.52481176]]
[[ 0.87101442  0.05480768  0.73031305 -1.26293697]]
[[ 0.57077426  0.3711482  -1.46088534  0.62100617]]
[[ 1.12340232 -1.63707897  0.98638101 -1.57012617]]
[[-0.75821658 -1.43475103 -0.62066696 -0.12337128]]
[[ 0.5825671  -1.14131617 -0.3518076  -0.95664442]]
[[ 0

[[-1.05042311 -1.48188152  0.4745003   1.03688013]]
[[ 2.46784161 -0.0251274  -0.69733846  1.59017515]]
[[-1.38088117  0.17662181 -0.10944155 -0.69277188]]
[[ 0.63660244 -2.48046425  0.02388848  0.0918154 ]]
[[ 1.35041013 -0.64865286  0.50646872 -0.13103136]]
[[-0.77549256  1.01830327  0.505519    0.18125149]]
[[-1.17480674  0.01188703 -1.26124526  0.55540895]]
[[-0.74295589 -1.711537    0.8037695   1.97384958]]
[[-1.52663128  0.36825157 -0.70828587  0.61839683]]
[[ 0.37256218 -0.37378344  0.84074804 -1.92087002]]
[[ 1.77643983 -0.45735633 -0.45902664  0.27429726]]
[[-1.19206419 -0.1192904  -0.44353775  1.56595122]]
[[ 2.0948448  -1.88977375  0.49432546 -0.02574403]]
[[-2.49143633  0.96167483  0.8416539  -0.52998278]]
[[ 0.66993352 -0.52731325  2.0408991  -1.30618202]]
[[ 0.30325504 -0.34796987 -0.26644076  1.92467965]]
[[-0.65856203 -0.38189049 -0.19674482 -0.27114806]]
[[-0.11965764 -0.41765138 -1.94069431  0.48991348]]
[[-0.11479525 -1.04708829 -1.33117638 -1.81052936]]
[[ 1.2843845

[[-2.80825731 -0.29669828 -0.53587244  1.28882378]]
[[1.42587186 0.07881317 0.36079912 0.46526918]]
[[ 0.70747886 -0.40496421 -2.37740771 -1.49035477]]
[[-0.64175463  0.46977952  0.00827487 -0.14111918]]
[[ 0.25470263 -0.23710566  0.28039984  0.96567857]]
[[-0.41573427  0.0534692  -0.9428644   0.9689442 ]]
[[-0.03115957 -0.29923336  1.74126022 -1.69820119]]
[[ 0.85648243  0.44275298  0.32679395 -1.01313763]]
[[ 0.50913448 -1.09723678 -0.14477175  0.20822446]]
[[-0.08943066 -0.52011615 -0.878067    2.11976292]]
[[-1.13456266  1.05352994  0.82499173  0.88005879]]
[[ 0.0410773   1.66980662 -0.92650822  0.38501196]]
[[-0.63971892 -1.03130788  2.70068359 -0.40165845]]
[[-0.80568627 -1.39467322 -1.57393433  0.47568902]]
[[-0.49544713 -0.37456248  0.77570786 -0.48502475]]
[[ 2.42622187 -0.7282121  -0.8280957  -0.45178374]]
[[-0.37146356  0.48867756  1.55392667  0.07668845]]
[[-0.70626684  0.95068577 -1.68901666 -0.41014154]]
[[0.69337126 0.184338   0.47972894 1.54788864]]
[[ 0.13705675 -0.195

[[ 0.15219514 -0.27220969  0.52147863 -0.14629238]]
[[-0.75174716 -0.31143778 -0.65219069  0.76553144]]
[[ 0.16623032 -0.75809224  1.89862203  0.88759036]]
[[-0.05406402  0.4480579  -1.12932684  0.27389476]]
[[-0.66740974 -1.65917492 -0.98332088 -0.36633441]]
[[ 0.46161556 -0.66882713 -0.62055133 -1.53535517]]
[[ 0.24840184  1.46905618  1.22677613 -0.63013091]]
[[ 0.32405234  0.71821012 -0.37025387  1.21586596]]
[[ 1.0357399  -0.60348862 -0.0987841  -0.06529552]]
[[-0.99430155  0.51030212 -2.14705662  0.50533318]]
[[ 0.39454195  0.18228071 -1.2156438   0.13956963]]
[[-1.1283947  -1.64937325  3.16250931  2.29605575]]
[[0.43798464 1.70235421 1.9124724  1.36720822]]
[[-0.47815516 -0.37902099 -1.67626682 -0.36443851]]
[[-1.33997421  0.63897616 -0.1864702  -1.10497508]]
[[-1.32038176  0.65635325  0.48790105  1.67078246]]
[[ 1.35395497  0.84928363 -0.75561865 -0.70353409]]
[[ 0.25124296  0.8319246  -2.8822799  -1.56248607]]
[[ 0.25348023 -0.67678362 -0.29654598  0.51666822]]
[[-0.8915872   0

[[-0.52016218  1.61003002  0.04716789 -0.99580938]]
[[0.45521092 0.1118101  1.79557571 0.41494844]]
[[-1.39896358 -0.3208602   0.88961087  1.21644815]]
[[-0.67292349  0.43643221 -0.36310881  0.03495369]]
[[ 1.13859785  0.33957728 -0.3404358  -2.16963418]]
[[-0.21081595 -1.5138192  -0.29909853 -0.00417115]]
[[-0.58345083  0.68910421  0.79628838 -0.46373591]]
[[-0.38726602  0.56802983  0.28998638 -0.33635933]]
[[-0.38399484 -1.13310057 -1.0300333   0.51228774]]
[[-0.74308632 -2.05031017  0.26968444 -2.0956284 ]]
[[ 0.74249813 -1.76244946 -0.89544234  1.71253236]]
[[ 0.80543927 -0.47002985 -0.24097625  0.62603123]]
[[ 1.43491194 -0.90427455  0.85174925 -2.51977703]]
[[-0.60542537  0.52712856 -2.46825429 -0.19316368]]
[[-1.32427222 -0.5069139   0.10786254  0.16512437]]
[[-1.01936167  0.25990705  0.13366538  1.72870533]]
[[-0.31895632  2.12551725 -0.99166449 -0.48930534]]
[[-0.55853859  1.0125302  -1.90971084  1.08894482]]
[[1.36120474 0.43121341 0.42709624 0.02131238]]
[[-1.19030236 -0.255

[[-1.66075447 -1.5764851  -2.08806845 -1.00093172]]
[[-0.78284273  0.16882723 -2.12296935 -1.22312607]]
[[ 0.88566726 -0.32092494 -0.41289692 -1.00827101]]
[[-1.5470506  -0.04156952  1.05054302  0.5088515 ]]
[[ 1.18463322 -0.30217808 -0.23736267 -1.1627165 ]]
[[ 1.05173757 -1.13916391  1.15161014  0.72514499]]
[[-0.36071947 -0.23077115  1.47706874 -0.32742745]]
[[-0.71455255 -0.58185293  1.03656512 -0.21670734]]
[[-0.88644713 -0.86083158 -0.59125233  0.51755342]]
[[-0.3784014   0.12927596 -1.22939825 -0.48328113]]
[[-0.12874247  0.66253608  0.219712   -0.39586187]]
[[-0.5789061  -1.32257566 -0.33388422 -1.12559166]]
[[ 0.52572302  1.73553619 -0.42044577 -0.29030851]]
[[-0.1658802  -0.04665363  1.04346238  0.03823533]]
[[-0.25854472  1.45390769  0.75084527  0.35209721]]
[[ 0.06775478 -0.17993608 -0.12078582  0.15974916]]
[[ 0.19460132 -1.02685187 -0.50373318  1.83090416]]
[[ 0.57924707  0.16456193  0.77724431 -0.26787578]]
[[-0.26279903  1.16172318 -1.44473615 -0.99599436]]
[[ 1.6650847

[[ 2.11678524 -0.02135729  0.23880909 -1.0907537 ]]
[[1.31926549 0.22711208 0.47714189 1.10704962]]
[[ 0.08458893  0.43262983 -0.59719305 -1.39829091]]
[[ 0.27301589 -0.47013344 -0.95966476  1.75670509]]
[[ 1.07689343  1.04294848 -1.90251243 -2.56028301]]
[[ 1.31325896 -0.78190637 -1.55207459  0.09277784]]
[[ 0.50487393  1.43571083  0.10509621 -0.79639439]]
[[ 0.04867126 -1.68759736  0.07163754 -0.51665635]]
[[-1.14338372  2.25666196  0.18797247 -0.97381777]]
[[-0.35848147  0.40936307  0.83854874  3.36051893]]
[[ 0.66451346 -1.12209202  0.07996281 -0.18585555]]
[[-0.61469244 -0.26038343 -1.09019905  0.50410948]]
[[-0.49369667 -0.56105304  0.64766745 -0.203484  ]]
[[-0.74308789  0.70190146  0.32684566  0.03574563]]
[[0.26216828 0.05594088 0.46065076 0.33009892]]
[[ 1.3338983  -1.50790993 -0.14572455  0.22042653]]
[[-0.63135408 -0.57831822  0.78873355 -0.64909323]]
[[ 0.50462988  0.15948424 -0.45240617 -1.87818148]]
[[-1.57650212 -0.1328494   0.31643978  1.14292932]]
[[ 0.03763041 -0.103

[[-0.71026222  0.29160284 -1.27289082  0.83687583]]
[[ 0.07905754 -0.99527043 -0.01847214 -1.27907312]]
[[ 0.58673348 -0.28220402  1.42992487  1.56063311]]
[[ 0.40190584 -0.87610032  1.71325055  0.65086707]]
[[-1.59176733  2.83814428 -0.45548206 -0.83467372]]
[[-0.43311351 -2.03953325  0.03064514 -2.00167646]]
[[1.52326549 1.27483818 0.17949733 0.11398277]]
[[ 0.35248327 -0.74657144 -0.39771897 -0.62834462]]
[[ 0.1551659   0.38759618 -2.14174971  0.13275044]]
[[ 0.59133494 -1.30538323  0.39452848 -0.64726336]]
[[-1.79720923  0.04412017  0.8534498  -0.55292776]]
[[-1.62966321 -0.00458378  0.95686585  1.21493307]]
[[-0.1390939   0.13032672  1.42123275 -1.15740915]]
[[-0.0268254  -0.46699726  0.2019748  -0.45971293]]
[[ 0.21582149 -1.39043698  0.90341162 -0.52844098]]
[[ 0.72224682 -0.80060324 -0.24612907  1.38567878]]
[[-0.38785599 -2.37913691  0.43519681 -1.25154047]]
[[1.41402841 0.72022623 1.28060018 1.61576074]]
[[-0.54729583  0.30938892 -1.278687    1.48184508]]
[[-1.34722872  0.504

[[ 0.66451362 -1.93925769  0.05331125  1.91241234]]
[[ 0.90956599  0.59507754 -0.96925453  0.43231685]]
[[-1.75089523 -0.32575992  0.69591401 -0.56818554]]
[[-0.55300114 -2.71388603 -0.46379285 -0.01227775]]
[[-0.53175624  0.84187946 -1.64734513  1.05862361]]
[[0.58956689 1.0386834  0.76730753 0.5708443 ]]
[[ 0.17483952  0.03029902  0.36625204 -0.50063546]]
[[ 0.04891893 -0.69610537 -0.24115358 -0.89384736]]
[[-0.86040896 -0.96793606 -1.32045552 -0.28123718]]
[[ 1.01924676  0.48782568  0.13961033 -1.51082034]]
[[-1.29580645  0.74066937 -1.14819448  0.14790341]]
[[ 1.06978569 -1.30093809 -0.76873464 -1.97627059]]
[[-0.06944936 -0.37462794 -0.23005345  1.02115371]]
[[-1.81111997 -0.7762452   1.10498879  0.05879879]]
[[ 0.11156455  0.75823743  0.76220961 -2.57075347]]
[[-0.8221934  -0.98686929  0.68071957  0.48850852]]
[[-0.19453384  1.44300897  0.16472689 -1.5830712 ]]
[[0.88897357 0.85617842 0.28941182 1.32261507]]
[[-0.75666808  0.49401632 -0.09273061 -2.55090525]]
[[-0.48415657  0.847

[[-0.75278719 -0.89957883 -0.58514946 -1.91463428]]
[[-1.60619125 -0.17747679  0.40804925  0.53900443]]
[[-1.94465901 -1.39155901  0.34983059  0.39009163]]
[[-0.46342574  0.81075949 -0.03804736  0.21971662]]
[[ 0.16818648  1.22198175  0.98481368 -1.32819231]]
[[ 1.07044907 -0.64270867 -1.9882098   0.73374066]]
[[0.50151799 0.68712973 1.16739387 1.35115118]]
[[-0.69522228 -1.21435834  0.56432801  0.55449106]]
[[-0.08446061 -0.82823395  1.67237124  0.94293343]]
[[ 1.71809277  0.06631965  0.6159337  -2.02806141]]
[[-1.52143594 -0.48977162 -2.10232594  0.18996459]]
[[-1.26734631  1.39166007  2.31728447  1.29455333]]
[[-0.84685274  0.56353371 -0.55516504  1.07238065]]
[[ 1.90218164 -1.65058158  0.37998716 -0.74804349]]
[[-0.4939715   2.10201859 -0.19714793 -1.09301659]]
[[ 0.11179924  1.12548121 -1.51573893  1.93688217]]
[[-0.91562685  0.69332509  1.69159196  0.67122611]]
[[ 0.1667453  -1.06464175  0.63248669  1.72380889]]
[[ 1.43344688 -0.71237767 -0.0154409   1.02905262]]
[[-3.14381823  1

[[ 0.58292486  1.09293448 -0.59545836  1.81322219]]
[[ 2.03886362 -0.54929141 -1.10812044  0.7950034 ]]
[[-0.21168603  0.80774172  1.6601392  -0.66083043]]
[[-1.16251261 -0.54889756 -1.36281161 -0.82403497]]
[[-1.21435722  0.26724142  0.55544218  1.59655446]]
[[ 2.22608884  0.5014469  -0.87688606  0.79880807]]
[[-1.50574269  0.21504059  1.44453731 -1.17654491]]
[[-1.30268209 -1.35044224 -0.38023713  0.6609627 ]]
[[-0.37460006 -1.22857364  0.44043454 -0.22273873]]
[[-1.08801622 -1.3626467   0.0454073  -0.41714997]]
[[ 0.72424201  1.10801668 -0.11382784  0.41579549]]
[[ 1.03123507  0.94591512 -0.85343261 -1.41869257]]
[[ 0.52934542 -0.57819331  1.66202975  1.53254498]]
[[ 0.59131366  1.03838957 -1.04229726  1.8161177 ]]
[[ 1.08698546  0.05008299  1.08644057 -0.59811559]]
[[-0.6755357   0.82476231  0.70155197  1.69710129]]
[[-0.83523684 -0.50263131 -1.04575485  0.46233553]]
[[ 0.21121936  0.3613878  -0.79355573 -1.61718406]]
[[-0.71725098 -0.10518299 -0.64771722  0.48079555]]
[[-1.1984303

[[-0.37127147 -0.18907309  0.2009603  -1.64165937]]
[[-0.11747463  0.79851909  1.53385698  1.14993246]]
[[ 0.50332371 -0.46503583 -0.74618862  0.83714952]]
[[ 1.80541894  0.3179005   0.94169786 -0.7279727 ]]
[[ 0.38277205 -0.32988891 -1.03754386 -1.99962333]]
[[ 0.382187    1.70655701  0.59603398 -0.43532606]]
[[-0.82676989  0.60996134  3.57665523 -1.32009564]]
[[-0.71689759  1.11906807 -0.66668456  1.86138857]]
[[-1.4663779  -1.44407016 -0.18603318  0.36502184]]
[[-0.58682772 -1.41662649 -1.22473608 -0.05148811]]
[[ 0.9902812  -0.28684903  0.63254257 -1.00771937]]
[[ 2.33841621 -0.08466289 -1.30273458  0.14957485]]
[[ 0.55970522  0.56617656 -0.46490884  0.06939512]]
[[ 1.62024023  2.03078711 -0.32525816 -1.87723659]]
[[ 0.38708975 -1.44150215  0.85874329 -1.1536241 ]]
[[ 0.11656618 -0.31567367 -1.16176002 -1.31010626]]
[[-1.02933433  1.76092662  0.32067945  0.21383304]]
[[-0.90196836 -0.87411201  0.1792507  -1.79906733]]
[[-0.14561117 -2.01467995 -1.12993021 -1.69665618]]
[[ 0.1654794

[[-0.97067785 -1.13368995  0.78139035  0.66620597]]
[[1.1867741  0.40275756 1.02237117 0.78579516]]
[[ 0.32159586 -1.16917152 -1.11910972 -1.4118909 ]]
[[-0.81018766  0.14842133 -0.37846864 -1.34253368]]
[[-0.09653977  0.22319535 -0.27533806 -2.58918439]]
[[-1.21644499 -0.29104011 -0.3726886  -0.0663532 ]]
[[ 1.07728776 -1.17113654 -2.42573959  0.333881  ]]
[[ 1.18697832  0.30971654 -1.17681285 -0.76875841]]
[[-0.50886434  0.4538652   0.0603624   0.31072964]]
[[ 0.00271036 -0.96844998 -2.14114056  1.62974836]]
[[ 0.66371322 -1.29988069  0.98279428  1.60785751]]
[[1.47218487 0.70494794 0.38603133 0.59301665]]
[[-0.63373126 -1.43287555 -0.20283833  0.188037  ]]
[[-0.61350874  0.1160788   0.18522999  1.36541056]]
[[-1.19148787  0.88859708  0.12909372  0.09257265]]
[[ 0.38783567 -1.03386681  1.32122258  1.33226236]]
[[ 0.34565329 -0.60603342 -1.53279887  0.96737997]]
[[ 0.13145678  2.06633838  0.03698221 -0.99406428]]
[[-0.48362207 -0.72119075 -0.91119626 -0.63696909]]
[[ 0.19633075 -0.706

[[1.05722035 0.73099495 1.42847128 1.08892662]]
[[-3.04705063  1.53104249  0.34970044 -0.8445991 ]]
[[-0.54954499  0.80670387 -2.22792128 -0.8890317 ]]
[[-1.07756739  0.3015797   0.37007425  1.20408828]]
[[ 0.14935997 -0.25467624  1.42171746 -1.08583859]]
[[-0.03109848  0.66443013  0.19311204  0.67926509]]
[[-1.67101556  1.1365603   0.62161385  2.5654227 ]]
[[ 1.25425241e+00  1.49030314e+00 -1.07980708e-03  1.12867593e+00]]
[[ 0.37645058 -0.45347661  0.70067674 -0.55004551]]
[[-0.57444639  1.39118989 -2.31390689  0.17194816]]
[[-1.31677003 -0.39464516 -0.36904704 -1.30407277]]
[[0.1142871  0.74891839 0.11892419 1.39418922]]
[[ 1.9471116   1.67423914 -1.9170061   0.68668598]]
[[-0.04165071  0.15824961 -0.47693383 -0.54806066]]
[[ 1.22339377  1.41538965  0.06632118 -0.28005877]]
[[ 0.56968893 -1.36829329  0.37572745  1.59104912]]
[[ 1.31479883 -0.72143655  0.14996964 -1.06473663]]
[[ 1.30842425  0.12872736  0.2305387  -0.49742237]]
[[ 1.3004909  -0.28934107 -0.43688513 -0.92237048]]
[[-0

[[ 1.01652103 -1.35153893 -1.31702807 -0.61443748]]
[[ 0.02796429  0.25260015 -0.95055168 -0.1890356 ]]
[[-0.29048789  0.14860893 -1.83811528  0.76604169]]
[[ 1.2534008   0.81452697  0.88314892 -0.49242669]]
[[-0.27866496  0.70752007  0.6832646   0.32333949]]
[[-0.09315358 -0.31368404 -0.51032084  0.14322151]]
[[-0.5286485  -1.83819337 -0.22589232 -1.09565778]]
[[-0.08739685 -0.08043863 -1.85730749 -0.81914542]]
[[ 1.09790828 -0.19875067 -1.02946961 -2.1851362 ]]
[[ 0.94908263 -0.87074242 -1.88043016  0.74843216]]
[[ 0.30758367  1.56599656 -1.12088085 -1.61436221]]
[[-0.03411763 -0.30373896 -0.3085489   1.28407817]]
[[ 0.74968513 -0.04766736 -0.10343716 -1.09435671]]
[[ 1.0378155  -1.334839   -0.26813945  0.80305084]]
[[0.10820074 0.92378585 0.78462424 1.00309566]]
[[-1.43514134  1.4514961  -0.37232776 -1.37375169]]
[[-0.8686849   0.90151738 -0.06252618 -0.93847852]]
[[ 0.01865521  0.90938474  1.02394798 -0.30862761]]
[[ 0.91343848 -0.92428389 -0.63312043 -1.19361323]]
[[ 1.6253585  -1

KeyboardInterrupt: 